name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test with coverage
        run: |
          dotnet test api.tests/api.tests.csproj -c Release -v minimal \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=cobertura \
            "/p:ExcludeByFile=**/Migrations/*"

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: api.tests/TestResults/**/coverage.cobertura.xml